### ISSUE TITLE
401 Client Error in loading Llama2-7b model

### ISSUE THREAD

**Issue by wennycooper** [kennethleungty/Llama-2-Open-Source-LLM-CPU-Inference#3]
Hi, 
I tried to run the main.py and I got following error messages.
It looks like it failed to load the Llama2-7b model.
Any help will be appreciated.

$ python main.py 'How much is the minimum guarantee payable by adidas?'

==
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_errors.py", line 261, in hf_raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/api/models/models/llama-2-7b-chat.ggmlv3.q8_0.bin/revision/main

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspace/test/Llama-2-Open-Source-LLM-CPU-Inference/main.py", line 26, in <module>
    dbqa = setup_dbqa()
  File "/workspace/test/Llama-2-Open-Source-LLM-CPU-Inference/src/utils.py", line 44, in setup_dbqa
    llm = build_llm()
  File "/workspace/test/Llama-2-Open-Source-LLM-CPU-Inference/src/llm.py", line 21, in build_llm
    llm = CTransformers(model=cfg.MODEL_BIN_PATH,
  File "/usr/local/lib/python3.10/dist-packages/langchain/load/serializable.py", line 74, in __init__
    super().__init__(**kwargs)
  File "pydantic/main.py", line 339, in pydantic.main.BaseModel.__init__
  File "pydantic/main.py", line 1102, in pydantic.main.validate_model
  File "/usr/local/lib/python3.10/dist-packages/langchain/llms/ctransformers.py", line 70, in validate_environment
    values["client"] = AutoModelForCausalLM.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/ctransformers/hub.py", line 130, in from_pretrained
    config = config or AutoConfig.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/ctransformers/hub.py", line 47, in from_pretrained
    cls._update_from_repo(
  File "/usr/local/lib/python3.10/dist-packages/ctransformers/hub.py", line 69, in _update_from_repo
    path = snapshot_download(
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/_snapshot_download.py", line 186, in snapshot_download
    repo_info = api.repo_info(repo_id=repo_id, repo_type=repo_type, revision=revision, token=token)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/hf_api.py", line 1868, in repo_info
    return method(
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/hf_api.py", line 1678, in model_info
    hf_raise_for_status(r)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_errors.py", line 293, in hf_raise_for_status
    raise RepositoryNotFoundError(message, response) from e
huggingface_hub.utils._errors.RepositoryNotFoundError: 401 Client Error. (Request ID: Root=1-64b9e8a9-40a275255e2a52783534bb88;5565df67-c3e7-4849-ad18-f760c8a653fa)

Repository Not Found for url: https://huggingface.co/api/models/models/llama-2-7b-chat.ggmlv3.q8_0.bin/revision/main.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
Invalid username or password.
==

**Comment by wennycooper** [comment]
Oh, I should download the model to local first. The problem solved.

**Comment by kennethleungty** [comment]
Hi Wenny, glad that it is solved. I will update the README as well to relay this point
